package by.lomazki.calculator

object Constants {
    const val regex = "-|\\*|/|\\+|[\\d]+\\.+\\d+|[\\d]+"
    const val NUMBER_FORMAT = "#.#########"
    const val ZERO = "0"
    const val ONE = "1"
    const val TWO = "2"
    const val TREE = "3"
    const val FOUR = "4"
    const val FIVE = "5"
    const val SIX = "6"
    const val SEVEN = "7"
    const val EIGHT = "8"
    const val NINE = "9"
    const val MINUS = "-"
    const val PLUS = "+"
    const val DIV = "/"
    const val MULTIPLY = "*"
    const val DOT = "."
    const val EMPTY_STRING = ""
    const val END_IS_NOT_DIGIT = "The expression does not end with a digit"
    const val START_IS_NOT_DIGIT = "The expression does not start with a digit"
    const val MISTAKE_OPERATION = "Several operations in a row"
    const val DIVISION_BY_ZERO = "Division by zero is prohibited"
}
