package by.lomazki.calculator

const val regex = """/x|\+|-|\*|/|\(|\)|[\d+\.[0-9]]+|.+?/g"""
const val numberFormat = "#.#########"
const val ZERO = "0"
const val ONE = "1"
const val TWO = "2"
const val TREE = "3"
const val FOUR = "4"
const val FIVE = "5"
const val SIX = "6"
const val SEVEN = "7"
const val EIGHT = "8"
const val NINE = "9"
const val MINUS = "-"
const val PLUS = "+"
const val DIV = "/"
const val MULTIPLY = "*"
const val DOT = "."
const val EMPTY_STRING = ""
const val ERROR = "error"